config/routes.rb
SocialMessager::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show, :index]
  match 'auth/:provider/callback', to: 'providers#create'
  resources :providers, :only => [:create, :index, :destroy]
  resources :messages
end

app/models/message.rb
class Message
  STATUSES = {
    :new         => 'new',
    :sent        => 'sent',
    :processing  => 'processing'
  }

  include Mongoid::Document
  include Mongoid::Timestamps

  field :content
  field :status, :default => STATUSES[:new]
  field :sent_at, :type => DateTime

  validates_presence_of :content, :provider_ids
  attr_accessible :content, :provider_ids

  embedded_in :user
  has_and_belongs_to_many :providers, inverse_of: nil

  def perform_send
    return true unless status == STATUSES[:new]
    providers.each do |p|
      p.gateway.post_message content
    end
    self.status = STATUSES[:sent]
    self.sent_at = Time.now
    save!
  end
end

app/models/provider.rb
class Provider
  include Mongoid::Document
  field :nickname
  field :uid
  field :provider
  field :oauth_token
  field :oauth_secret

  belongs_to :user

  def gateway
    return @gateway if @gateway
    @gateway = Twitter::Client.new(:oauth_token => oauth_token, :oauth_token_secret => oauth_secret) if provider == 'twitter'
    @gateway = VK::Serverside.new :app_id => ENV['API_KEY'], :app_secret => ENV['API_SECRET'], :access_token => oauth_token if provider == 'vkontakte'
    GatewayAdapter.new @gateway, provider
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
  # run 'rake db:mongoid:create_indexes' to create indexes
  index :email, :unique => true
  field :name
  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :encrypted_password

  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  has_many :providers
  embeds_many :messages

  def provider_from_omniauth(auth)
    providers.where(auth.slice('provider', 'uid')).first || create_provider_from_omniauth(auth)
  end

  def create_provider_from_omniauth(auth)
    providers.create! do |provider|
      provider.provider = auth['provider']
      provider.uid = auth['uid']
      provider.nickname = auth['info']['nickname']
      provider.oauth_token = auth['credentials']['token']
      provider.oauth_secret = auth['credentials']['secret']
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :check_providers, :only => [:edit, :create, :new, :update]

  def index
    @messages = current_user.messages
  end

  def new
    @message = Message.new
  end

  def create
    @message = current_user.messages.build params[:message]
    if @message.save
      redirect_to messages_path, notice: 'Message was successfully created.'
    else
      render "new"
    end
  end

  def edit
    @message = current_user.messages.find params[:id]
  end

  def update
    @message = current_user.messages.find params[:id]
    if @message.update_attributes params[:message]
      redirect_to messages_path, notice: 'Message was successfully updated.'
    else
      render "edit"
    end
  end

  def destroy
    @message = current_user.messages.find params[:id]
    @message.destroy
    redirect_to messages_path, notice: 'Message was successfully deleted.'
  end

  private

  def check_providers
    if current_user.providers.count == 0
      redirect_to providers_path, :alert => 'You should connect providers, before creating messages'
    end
  end

end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @providers = current_user.providers
  end

  def create
    @provider = current_user.provider_from_omniauth(env["omniauth.auth"])
    redirect_to providers_path, :notice => "Successfully connected to #{@provider.provider}"
  end

  def destroy
    @provider = current_user.providers.find params['id']
    @provider.destroy
    redirect_to providers_path, :notice => "Provider successfully deleted."
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h3>Home</h3>
<% @users.each do |user| %>
  <p>User: <%=link_to user.name, user %></p>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Social Messager", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li><%= link_to 'Messages', messages_path %></li>
    <li><%= link_to 'Providers', providers_path %></li>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>        
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Social Messager" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.error_notification %>

  <%= f.input :content, :as => :text, :required => true, :autofocus => true, :input_html => { :size => '20x7' } %>
  <%= f.association :providers, :collection => current_user.providers.map{ |p| [p.provider, p.id] }, :as => :check_boxes %>

  <div class="form-actions">
    <%= f.button :submit, @message.new_record? ? 'Create' : 'Save' %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div>
  Created at: <%= message.created_at %>, status: <%= message.status %>
  <p><%= message.content %></p>
  <div>
    <%= link_to 'Edit', edit_message_path(message) %>
    <%= link_to 'Delete', message_path(message), :method => :delete %>
  </div>
</div>

app/views/messages/edit.html.erb
<h1>Update message</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
<h1>Messages</h1>
<br />
<%= link_to 'New message', new_message_path, :class => 'btn' %>
<br />

<div class="well">
  <%= render @messages %>
</div>

app/views/messages/new.html.erb
<h2>New Message</h2>

<%= render 'form' %>

app/views/providers/index.html.erb
<h1>Providers</h1>
<div class="well">
  <%= link_to 'Connect to Twitter', '/auth/twitter' %><br />
  <%= link_to 'Connect to Facebook', '/auth/facebook' %><br />
  <%= link_to 'Connect to VK.com', '/auth/vkontakte' %><br />
</div>
<ul>
<% @providers.each do |provider| %>
  <li><%= provider.nickname %> - <%= provider.provider %> <%= link_to 'Delete', provider_path(provider), :confirm => 'Are you sure to delete this provider?', :method => :delete %></li>
<% end %>
</ul>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>